name: Compile Android APK

on:
  push:
    branches: [ master, NET10 ]
  pull_request:
    branches: [ master ]
  release:
     types: 
       - published
       - prereleased
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json 
       
    - name: Install Android Workload
      run: dotnet workload install android

    # Генерируем ключ в корне рабочей директории
    - name: Generate Test Keystore
      run: |
        keytool -genkey -v -keystore test.keystore -alias testalias -keyalg RSA -keysize 2048 -validity 10000 -storepass password -keypass password -dname "CN=Test, OU=Test, O=Test, L=Test, S=Test, C=US"

    - name: Restore dependencies
      run: dotnet restore GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj

    # ИСПРАВЛЕНО: Указан полный путь к keystore: ${{ github.workspace }}/test.keystore
    - name: Build Android APK (Signed)
      run: >
        dotnet publish GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj
        -f net10.0-android36.1
        -r android-arm64
        -c Release
        -p:AndroidPackageFormats=apk
        -p:AndroidKeyStore=true
        -p:AndroidSigningKeyStore=${{ github.workspace }}/test.keystore
        -p:AndroidSigningKeyAlias=testalias
        -p:AndroidSigningKeyPass=password
        -p:AndroidSigningStorePass=password
        -p:BuildInParallel=false
        -p:TreatWarningsAsErrors=false
        -p:NoWarn="IL2037;CS1591;XA0141"
        --no-restore

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GalaxyBudsClient_Android_arm64
        path: GalaxyBudsClient.Android/bin/Release/net10.0-android36.1/android-arm64/publish/*-Signed.apk

  attach-to-release:
    runs-on: ubuntu-latest
    needs: [build-android]
    if: github.event_name == 'release'
     
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: GalaxyBudsClient_Android_arm64
    
    - name: Rename APK
      run: mv *-Signed.apk GalaxyBudsClient_Android_arm64.apk

    - uses: AButler/upload-release-assets@v3.0
      with:
        files: '*.apk'
        repo-token: ${{ secrets.GH_TOKEN }}
